"""Create all tables

Revision ID: 949902ff763d
Revises: 
Create Date: 2026-03-20 14:22:18.238086+08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949902ff763d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aa_customer_criteria',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('condition_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('A_BASIC_INFO', 'B_PROPERTY', 'C_BUSINESS', 'D_DIGITAL', name='questioncategory'), nullable=False),
    sa.Column('visit_type', sa.Enum('FIRST_VISIT', 'SECOND_VISIT', 'FOLLOW_UP', name='visittype'), nullable=False),
    sa.Column('priority', sa.Enum('REQUIRED', 'RECOMMENDED', 'OPTIONAL', name='questionpriority'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('TEXT', 'TEXTAREA', 'NUMBER', 'SELECT', 'MULTISELECT', 'BOOLEAN', 'DATE', 'URL', name='questiontype'), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('score_weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_visit_type', 'question_templates', ['category', 'visit_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('SALES', 'MANAGER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('team', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('is_aa_customer', sa.Boolean(), nullable=False),
    sa.Column('customer_stage', sa.Enum('INDIVIDUAL', 'PREPARING_COMPANY', 'NEW_COMPANY', 'SCALING_UP', name='customerstage'), nullable=True),
    sa.Column('maturity_score', sa.Integer(), nullable=True),
    sa.Column('basic_info', sa.JSON(), nullable=True),
    sa.Column('current_status', sa.Enum('CONTACTED', 'FIRST_VISIT_SCHEDULED', 'FIRST_VISIT_DONE', 'SECOND_VISIT_SCHEDULED', 'SECOND_VISIT_DONE', 'NEGOTIATING', 'SIGNED', 'LOST', name='customerstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_company_name', 'customers', ['company_name'], unique=False)
    op.create_index('idx_current_status', 'customers', ['current_status'], unique=False)
    op.create_index('idx_customer_stage', 'customers', ['customer_stage'], unique=False)
    op.create_index('idx_is_aa_customer', 'customers', ['is_aa_customer'], unique=False)
    op.create_table('performance_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('metric_period', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', name='metricperiod'), nullable=False),
    sa.Column('total_visits', sa.Integer(), nullable=False),
    sa.Column('first_visits', sa.Integer(), nullable=False),
    sa.Column('second_visits', sa.Integer(), nullable=False),
    sa.Column('follow_up_visits', sa.Integer(), nullable=False),
    sa.Column('contracts_signed', sa.Integer(), nullable=False),
    sa.Column('aa_customers_acquired', sa.Integer(), nullable=False),
    sa.Column('conversion_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metric_date', 'performance_metrics', ['metric_date'], unique=False)
    op.create_index('idx_user_metric_date', 'performance_metrics', ['user_id', 'metric_date'], unique=False)
    op.create_table('visits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('visit_type', sa.Enum('FIRST_VISIT', 'SECOND_VISIT', 'FOLLOW_UP', name='visittype'), nullable=False),
    sa.Column('visit_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('visit_status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', 'RESCHEDULED', name='visitstatus'), nullable=False),
    sa.Column('basic_info', sa.JSON(), nullable=True),
    sa.Column('property_status', sa.JSON(), nullable=True),
    sa.Column('development_plan', sa.JSON(), nullable=True),
    sa.Column('business_status', sa.JSON(), nullable=True),
    sa.Column('digitalization', sa.JSON(), nullable=True),
    sa.Column('pain_points', sa.Text(), nullable=True),
    sa.Column('client_needs', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_action', sa.String(length=255), nullable=True),
    sa.Column('next_visit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_customer_id', 'visits', ['customer_id'], unique=False)
    op.create_index('idx_visit_date', 'visits', ['visit_date'], unique=False)
    op.create_index('idx_visit_status', 'visits', ['visit_status'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('visit_id', sa.String(length=36), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=False),
    sa.Column('contract_type', sa.Enum('PACKAGE_RENTAL', 'PROPERTY_MGMT', 'SUBLEASE', 'HYBRID', name='contracttype'), nullable=False),
    sa.Column('property_count', sa.Integer(), nullable=True),
    sa.Column('monthly_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('kpi_property_upload_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('kpi_contract_creation_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('kpi_billing_active', sa.Boolean(), nullable=False),
    sa.Column('kpi_payment_integrated', sa.Boolean(), nullable=False),
    sa.Column('kpi_notification_setup', sa.Boolean(), nullable=False),
    sa.Column('kpi_sop_established', sa.Boolean(), nullable=False),
    sa.Column('onboarding_success', sa.Boolean(), nullable=False),
    sa.Column('onboarding_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contract_date', 'contracts', ['contract_date'], unique=False)
    op.create_index('idx_customer_id', 'contracts', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_customer_id', table_name='contracts')
    op.drop_index('idx_contract_date', table_name='contracts')
    op.drop_table('contracts')
    op.drop_index('idx_visit_status', table_name='visits')
    op.drop_index('idx_visit_date', table_name='visits')
    op.drop_index('idx_customer_id', table_name='visits')
    op.drop_table('visits')
    op.drop_index('idx_user_metric_date', table_name='performance_metrics')
    op.drop_index('idx_metric_date', table_name='performance_metrics')
    op.drop_table('performance_metrics')
    op.drop_index('idx_is_aa_customer', table_name='customers')
    op.drop_index('idx_customer_stage', table_name='customers')
    op.drop_index('idx_current_status', table_name='customers')
    op.drop_index('idx_company_name', table_name='customers')
    op.drop_table('customers')
    op.drop_table('users')
    op.drop_index('idx_category_visit_type', table_name='question_templates')
    op.drop_table('question_templates')
    op.drop_table('aa_customer_criteria')
    # ### end Alembic commands ###
