"""add missing columns to visits

Revision ID: 783d2fea4f3b
Revises: 75312805a79b
Create Date: 2026-04-08 15:45:49.519340+08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783d2fea4f3b'
down_revision = '75312805a79b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_index('idx_contracts_customer_id', table_name='contracts')
    op.create_index('idx_contract_customer_id', 'contracts', ['customer_id'], unique=False)
    op.alter_column('customers', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.add_column('visits', sa.Column('questionnaire_data', sa.JSON(), nullable=True))
    op.alter_column('visits', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_index('idx_visits_customer_id', table_name='visits')
    op.create_index('idx_visit_customer_id', 'visits', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_visit_customer_id', table_name='visits')
    op.create_index('idx_visits_customer_id', 'visits', ['customer_id'], unique=False)
    op.alter_column('visits', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('visits', 'questionnaire_data')
    op.alter_column('customers', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_index('idx_contract_customer_id', table_name='contracts')
    op.create_index('idx_contracts_customer_id', 'contracts', ['customer_id'], unique=False)
    op.alter_column('contracts', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###
