"""add missing columns to visits

Revision ID: 783d2fea4f3b
Revises: 75312805a79b
Create Date: 2026-04-08 15:45:49.519340+08:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '783d2fea4f3b'
down_revision = '75312805a79b'
branch_labels = None
depends_on = None


def _column_exists(table_name: str, column_name: str) -> bool:
    """檢查欄位是否已存在"""
    bind = op.get_bind()
    insp = inspect(bind)
    columns = [c['name'] for c in insp.get_columns(table_name)]
    return column_name in columns


def _index_exists(table_name: str, index_name: str) -> bool:
    """檢查索引是否已存在"""
    bind = op.get_bind()
    insp = inspect(bind)
    indexes = [i['name'] for i in insp.get_indexes(table_name)]
    return index_name in indexes


def upgrade() -> None:
    # contracts.created_by nullable
    op.alter_column('contracts', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # 重命名 contracts index
    if _index_exists('contracts', 'idx_contracts_customer_id'):
        op.drop_index('idx_contracts_customer_id', table_name='contracts')
    if not _index_exists('contracts', 'idx_contract_customer_id'):
        op.create_index('idx_contract_customer_id', 'contracts', ['customer_id'], unique=False)

    # customers.created_by nullable
    op.alter_column('customers', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # visits.questionnaire_data
    if not _column_exists('visits', 'questionnaire_data'):
        op.add_column('visits', sa.Column('questionnaire_data', sa.JSON(), nullable=True))

    # visits.created_by nullable
    op.alter_column('visits', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # 重命名 visits index
    if _index_exists('visits', 'idx_visits_customer_id'):
        op.drop_index('idx_visits_customer_id', table_name='visits')
    if not _index_exists('visits', 'idx_visit_customer_id'):
        op.create_index('idx_visit_customer_id', 'visits', ['customer_id'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_visit_customer_id', table_name='visits')
    op.create_index('idx_visits_customer_id', 'visits', ['customer_id'], unique=False)
    op.alter_column('visits', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('visits', 'questionnaire_data')
    op.alter_column('customers', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_index('idx_contract_customer_id', table_name='contracts')
    op.create_index('idx_contracts_customer_id', 'contracts', ['customer_id'], unique=False)
    op.alter_column('contracts', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###
